# This is a basic workflow to help you get started with Actions

name: harvest:0.0

on:
  workflow_dispatch:
  
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: tamboraorg/crecoding:2020.0
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: master
      - name: remove existing news*.csv
        run: (rm -f csv/news_????_??.csv)
      - name: initialize regular harvest
        run: (sed -i 's/###REMOVE#BEFORE#FLIGHT###//' .github/workflows/harvest.yml)
      - name: remove init action itself
        run: (rm -f .github/workflows/init.yml)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'csv/news_????_??.csv .github/workflows/*.yml'
          tag_push: '--force'
